// Demo Dataset - Synthetic Marketing Data for TechNova Brand

export interface HistoricalPost {
  postId: string;
  platform: string;
  date: string;
  topic: string;
  subtopic: string;
  format: string;
  title: string;
  summary: string;
  targetAudience: string;
  views: number;
  likes: number;
  comments: number;
  shares: number;
  saves: number;
  engagementRate: number;
  outcome: 'high' | 'medium' | 'low';
}

export const historicalPosts: HistoricalPost[] = [
  // AI Content - Practical tutorials perform well
  {
    postId: 'post_001',
    platform: 'LinkedIn',
    date: '2026-08-15',
    topic: 'AI',
    subtopic: 'Practical Tutorial',
    format: 'Tutorial',
    title: 'Build Your First RAG Application in 10 Minutes',
    summary: 'Step-by-step guide to building a Retrieval-Augmented Generation app with Python and LangChain',
    targetAudience: 'Developers',
    views: 8500,
    likes: 420,
    comments: 67,
    shares: 89,
    saves: 145,
    engagementRate: 8.5,
    outcome: 'high'
  },
  {
    postId: 'post_002',
    platform: 'Twitter',
    date: '2026-08-18',
    topic: 'AI',
    subtopic: 'Practical Tutorial',
    format: 'Thread',
    title: 'Prompt Engineering Tips That Actually Work',
    summary: '7 proven techniques to improve your AI prompts with real examples',
    targetAudience: 'Developers',
    views: 12400,
    likes: 890,
    comments: 124,
    shares: 267,
    saves: 445,
    engagementRate: 13.9,
    outcome: 'high'
  },
  {
    postId: 'post_003',
    platform: 'LinkedIn',
    date: '2026-08-22',
    topic: 'AI',
    subtopic: 'News',
    format: 'News',
    title: 'Latest AI Model Releases This Week',
    summary: 'Overview of new AI models announced by major tech companies',
    targetAudience: 'General Tech',
    views: 4200,
    likes: 156,
    comments: 23,
    shares: 34,
    saves: 67,
    engagementRate: 6.7,
    outcome: 'medium'
  },
  {
    postId: 'post_004',
    platform: 'LinkedIn',
    date: '2026-09-01',
    topic: 'AI',
    subtopic: 'Practical Tutorial',
    format: 'Tutorial',
    title: 'Fine-Tuning LLMs on Your Own Data',
    summary: 'Complete guide to fine-tuning open-source language models with custom datasets',
    targetAudience: 'Developers',
    views: 9800,
    likes: 512,
    comments: 89,
    shares: 123,
    saves: 234,
    engagementRate: 9.8,
    outcome: 'high'
  },
  {
    postId: 'post_005',
    platform: 'Twitter',
    date: '2026-09-05',
    topic: 'AI',
    subtopic: 'Opinion',
    format: 'Opinion',
    title: 'Why AI Won\'t Replace Developers',
    summary: 'Discussion about the future of software development in the age of AI',
    targetAudience: 'Developers',
    views: 5600,
    likes: 234,
    comments: 78,
    shares: 45,
    saves: 89,
    engagementRate: 8.0,
    outcome: 'medium'
  },

  // Python Content - Automation tutorials perform well
  {
    postId: 'post_006',
    platform: 'LinkedIn',
    date: '2026-08-10',
    topic: 'Python',
    subtopic: 'Automation',
    format: 'Tutorial',
    title: 'Automate Your Daily Tasks With Python Scripts',
    summary: '5 practical Python scripts to automate file management, emails, and data processing',
    targetAudience: 'Developers',
    views: 11200,
    likes: 645,
    comments: 98,
    shares: 156,
    saves: 289,
    engagementRate: 10.6,
    outcome: 'high'
  },
  {
    postId: 'post_007',
    platform: 'Twitter',
    date: '2026-08-25',
    topic: 'Python',
    subtopic: 'Automation',
    format: 'Code Snippet',
    title: 'Python One-Liners That Will Save You Hours',
    summary: 'Collection of powerful Python one-liners for common tasks',
    targetAudience: 'Developers',
    views: 15600,
    likes: 1234,
    comments: 187,
    shares: 456,
    saves: 678,
    engagementRate: 16.4,
    outcome: 'high'
  },
  {
    postId: 'post_008',
    platform: 'LinkedIn',
    date: '2026-09-08',
    topic: 'Python',
    subtopic: 'Web Scraping',
    format: 'Tutorial',
    title: 'Web Scraping Best Practices 2026',
    summary: 'How to scrape websites ethically and efficiently with Python',
    targetAudience: 'Developers',
    views: 7800,
    likes: 398,
    comments: 56,
    shares: 87,
    saves: 167,
    engagementRate: 9.1,
    outcome: 'high'
  },
  {
    postId: 'post_009',
    platform: 'LinkedIn',
    date: '2026-09-12',
    topic: 'Python',
    subtopic: 'News',
    format: 'News',
    title: 'Python 3.13 Released: What\'s New',
    summary: 'Overview of new features in Python 3.13 release',
    targetAudience: 'Developers',
    views: 3400,
    likes: 123,
    comments: 19,
    shares: 28,
    saves: 45,
    engagementRate: 6.3,
    outcome: 'medium'
  },

  // Cybersecurity - Practical demonstrations perform well, awareness posts perform poorly
  {
    postId: 'post_010',
    platform: 'LinkedIn',
    date: '2026-08-12',
    topic: 'Cybersecurity',
    subtopic: 'Practical Demo',
    format: 'Tutorial',
    title: 'How to Hack Your Own API: Security Testing Demo',
    summary: 'Live demonstration of common API vulnerabilities and how to fix them',
    targetAudience: 'Developers',
    views: 13400,
    likes: 789,
    comments: 145,
    shares: 234,
    saves: 456,
    engagementRate: 12.1,
    outcome: 'high'
  },
  {
    postId: 'post_011',
    platform: 'Twitter',
    date: '2026-08-20',
    topic: 'Cybersecurity',
    subtopic: 'Practical Demo',
    format: 'Thread',
    title: 'I Tested 100 Websites for XSS Vulnerabilities',
    summary: 'What I found and how to protect your site with real examples',
    targetAudience: 'Developers',
    views: 18900,
    likes: 1567,
    comments: 267,
    shares: 445,
    saves: 778,
    engagementRate: 16.0,
    outcome: 'high'
  },
  {
    postId: 'post_012',
    platform: 'LinkedIn',
    date: '2026-08-28',
    topic: 'Cybersecurity',
    subtopic: 'Awareness',
    format: 'Infographic',
    title: 'Cybersecurity Awareness Month Tips',
    summary: 'General tips for staying safe online',
    targetAudience: 'General Tech',
    views: 2100,
    likes: 67,
    comments: 8,
    shares: 12,
    saves: 23,
    engagementRate: 5.2,
    outcome: 'low'
  },
  {
    postId: 'post_013',
    platform: 'LinkedIn',
    date: '2026-09-03',
    topic: 'Cybersecurity',
    subtopic: 'Awareness',
    format: 'Article',
    title: 'Why Cybersecurity Matters in 2026',
    summary: 'Generic overview of cybersecurity importance',
    targetAudience: 'General Tech',
    views: 1800,
    likes: 45,
    comments: 5,
    shares: 8,
    saves: 15,
    engagementRate: 4.1,
    outcome: 'low'
  },
  {
    postId: 'post_014',
    platform: 'Twitter',
    date: '2026-09-10',
    topic: 'Cybersecurity',
    subtopic: 'Practical Demo',
    format: 'Video',
    title: 'Live: Breaking Into a Docker Container',
    summary: 'Real-time demonstration of container escape techniques and prevention',
    targetAudience: 'Developers',
    views: 16700,
    likes: 1234,
    comments: 198,
    shares: 356,
    saves: 567,
    engagementRate: 14.1,
    outcome: 'high'
  },

  // Cloud Content - Mixed performance
  {
    postId: 'post_015',
    platform: 'LinkedIn',
    date: '2026-08-14',
    topic: 'Cloud',
    subtopic: 'AWS',
    format: 'Tutorial',
    title: 'Deploy a Serverless API in 5 Minutes',
    summary: 'Quick guide to AWS Lambda and API Gateway',
    targetAudience: 'Developers',
    views: 6700,
    likes: 289,
    comments: 45,
    shares: 67,
    saves: 123,
    engagementRate: 7.8,
    outcome: 'medium'
  },
  {
    postId: 'post_016',
    platform: 'LinkedIn',
    date: '2026-08-30',
    topic: 'Cloud',
    subtopic: 'Cost Optimization',
    format: 'Guide',
    title: 'How We Cut Our AWS Bill by 60%',
    summary: 'Practical strategies for reducing cloud costs',
    targetAudience: 'Developers',
    views: 8900,
    likes: 445,
    comments: 78,
    shares: 112,
    saves: 234,
    engagementRate: 9.8,
    outcome: 'high'
  },
  {
    postId: 'post_017',
    platform: 'Twitter',
    date: '2026-09-07',
    topic: 'Cloud',
    subtopic: 'News',
    format: 'News',
    title: 'AWS Announces New Services at re:Invent',
    summary: 'Summary of new AWS service announcements',
    targetAudience: 'General Tech',
    views: 3200,
    likes: 98,
    comments: 12,
    shares: 23,
    saves: 34,
    engagementRate: 5.2,
    outcome: 'medium'
  },

  // DevOps - Underrepresented topic
  {
    postId: 'post_018',
    platform: 'LinkedIn',
    date: '2026-08-16',
    topic: 'DevOps',
    subtopic: 'CI/CD',
    format: 'Tutorial',
    title: 'GitHub Actions for Complete Beginners',
    summary: 'Introduction to continuous integration with GitHub Actions',
    targetAudience: 'Developers',
    views: 5600,
    likes: 234,
    comments: 34,
    shares: 56,
    saves: 98,
    engagementRate: 7.5,
    outcome: 'medium'
  },
  {
    postId: 'post_019',
    platform: 'LinkedIn',
    date: '2026-09-14',
    topic: 'DevOps',
    subtopic: 'Docker',
    format: 'Tutorial',
    title: 'Docker Compose for Local Development',
    summary: 'Set up your development environment with Docker Compose',
    targetAudience: 'Developers',
    views: 6100,
    likes: 267,
    comments: 38,
    shares: 62,
    saves: 115,
    engagementRate: 7.9,
    outcome: 'medium'
  },

  // More AI content
  {
    postId: 'post_020',
    platform: 'LinkedIn',
    date: '2026-08-19',
    topic: 'AI',
    subtopic: 'Practical Tutorial',
    format: 'Tutorial',
    title: 'Build a Chat Bot with Memory in 20 Minutes',
    summary: 'Creating an AI chatbot that remembers conversation history',
    targetAudience: 'Developers',
    views: 10200,
    likes: 567,
    comments: 87,
    shares: 134,
    saves: 245,
    engagementRate: 10.1,
    outcome: 'high'
  },
  {
    postId: 'post_021',
    platform: 'Twitter',
    date: '2026-08-23',
    topic: 'AI',
    subtopic: 'Practical Tutorial',
    format: 'Code Snippet',
    title: 'Generate Images with Stable Diffusion API',
    summary: 'Code example for integrating image generation into your app',
    targetAudience: 'Developers',
    views: 9800,
    likes: 456,
    comments: 67,
    shares: 123,
    saves: 234,
    engagementRate: 9.0,
    outcome: 'high'
  },

  // More Python content
  {
    postId: 'post_022',
    platform: 'LinkedIn',
    date: '2026-08-26',
    topic: 'Python',
    subtopic: 'Data Science',
    format: 'Tutorial',
    title: 'pandas vs polars: Performance Comparison',
    summary: 'Benchmarking modern Python data processing libraries',
    targetAudience: 'Developers',
    views: 7400,
    likes: 345,
    comments: 56,
    shares: 89,
    saves: 156,
    engagementRate: 8.7,
    outcome: 'high'
  },
  {
    postId: 'post_023',
    platform: 'Twitter',
    date: '2026-09-02',
    topic: 'Python',
    subtopic: 'Automation',
    format: 'Code Snippet',
    title: 'Python Script to Organize Your Downloads Folder',
    summary: 'Automatically sort files by type and date',
    targetAudience: 'Developers',
    views: 8900,
    likes: 512,
    comments: 78,
    shares: 145,
    saves: 267,
    engagementRate: 11.2,
    outcome: 'high'
  },

  // More Cybersecurity
  {
    postId: 'post_024',
    platform: 'LinkedIn',
    date: '2026-09-06',
    topic: 'Cybersecurity',
    subtopic: 'Practical Demo',
    format: 'Tutorial',
    title: 'SQL Injection: Attack and Defense Demo',
    summary: 'Live demonstration of SQL injection with prevention techniques',
    targetAudience: 'Developers',
    views: 11800,
    likes: 678,
    comments: 123,
    shares: 198,
    saves: 345,
    engagementRate: 11.4,
    outcome: 'high'
  },
  {
    postId: 'post_025',
    platform: 'Twitter',
    date: '2026-09-11',
    topic: 'Cybersecurity',
    subtopic: 'Awareness',
    format: 'Infographic',
    title: 'Top 10 Password Security Tips',
    summary: 'Generic password security advice',
    targetAudience: 'General Tech',
    views: 1600,
    likes: 34,
    comments: 4,
    shares: 7,
    saves: 12,
    engagementRate: 3.6,
    outcome: 'low'
  },

  // More Cloud content
  {
    postId: 'post_026',
    platform: 'LinkedIn',
    date: '2026-08-17',
    topic: 'Cloud',
    subtopic: 'Architecture',
    format: 'Guide',
    title: 'Microservices vs Monolith: Real Experience',
    summary: 'Lessons learned from migrating to microservices',
    targetAudience: 'Developers',
    views: 6800,
    likes: 312,
    comments: 67,
    shares: 89,
    saves: 145,
    engagementRate: 9.0,
    outcome: 'high'
  },
  {
    postId: 'post_027',
    platform: 'LinkedIn',
    date: '2026-09-04',
    topic: 'Cloud',
    subtopic: 'Security',
    format: 'Tutorial',
    title: 'Secure Your Cloud Infrastructure Checklist',
    summary: 'Essential security practices for cloud deployments',
    targetAudience: 'Developers',
    views: 5900,
    likes: 267,
    comments: 45,
    shares: 72,
    saves: 123,
    engagementRate: 8.6,
    outcome: 'medium'
  },

  // Additional varied content
  {
    postId: 'post_028',
    platform: 'LinkedIn',
    date: '2026-08-21',
    topic: 'AI',
    subtopic: 'Ethics',
    format: 'Opinion',
    title: 'Responsible AI Development Practices',
    summary: 'Discussion on ethical considerations in AI development',
    targetAudience: 'Developers',
    views: 4200,
    likes: 178,
    comments: 34,
    shares: 45,
    saves: 78,
    engagementRate: 8.0,
    outcome: 'medium'
  },
  {
    postId: 'post_029',
    platform: 'Twitter',
    date: '2026-08-24',
    topic: 'Python',
    subtopic: 'Testing',
    format: 'Thread',
    title: 'pytest Tips for Better Test Coverage',
    summary: 'Advanced pytest techniques and best practices',
    targetAudience: 'Developers',
    views: 6700,
    likes: 334,
    comments: 56,
    shares: 89,
    saves: 167,
    engagementRate: 9.6,
    outcome: 'high'
  },
  {
    postId: 'post_030',
    platform: 'LinkedIn',
    date: '2026-08-27',
    topic: 'DevOps',
    subtopic: 'Monitoring',
    format: 'Tutorial',
    title: 'Set Up Application Monitoring in 10 Minutes',
    summary: 'Quick guide to monitoring with Prometheus and Grafana',
    targetAudience: 'Developers',
    views: 5400,
    likes: 234,
    comments: 38,
    shares: 61,
    saves: 112,
    engagementRate: 8.2,
    outcome: 'medium'
  },
  {
    postId: 'post_031',
    platform: 'LinkedIn',
    date: '2026-08-31',
    topic: 'AI',
    subtopic: 'Practical Tutorial',
    format: 'Tutorial',
    title: 'Vector Databases Explained with Code',
    summary: 'Introduction to vector databases with practical examples',
    targetAudience: 'Developers',
    views: 8700,
    likes: 445,
    comments: 72,
    shares: 115,
    saves: 223,
    engagementRate: 9.8,
    outcome: 'high'
  },
  {
    postId: 'post_032',
    platform: 'Twitter',
    date: '2026-09-09',
    topic: 'Python',
    subtopic: 'Performance',
    format: 'Thread',
    title: 'Make Your Python Code 10x Faster',
    summary: 'Performance optimization techniques with benchmarks',
    targetAudience: 'Developers',
    views: 13400,
    likes: 891,
    comments: 134,
    shares: 267,
    saves: 445,
    engagementRate: 13.0,
    outcome: 'high'
  },
  {
    postId: 'post_033',
    platform: 'LinkedIn',
    date: '2026-09-13',
    topic: 'Cloud',
    subtopic: 'Kubernetes',
    format: 'Guide',
    title: 'Kubernetes Fundamentals for Developers',
    summary: 'Understanding Kubernetes concepts with practical examples',
    targetAudience: 'Developers',
    views: 7100,
    likes: 323,
    comments: 52,
    shares: 87,
    saves: 156,
    engagementRate: 8.7,
    outcome: 'high'
  },
  {
    postId: 'post_034',
    platform: 'LinkedIn',
    date: '2026-09-15',
    topic: 'Cybersecurity',
    subtopic: 'Practical Demo',
    format: 'Video',
    title: 'Hacking WiFi Networks: Demo and Prevention',
    summary: 'Educational demonstration of network security vulnerabilities',
    targetAudience: 'Developers',
    views: 14500,
    likes: 823,
    comments: 167,
    shares: 289,
    saves: 456,
    engagementRate: 12.0,
    outcome: 'high'
  },
  {
    postId: 'post_035',
    platform: 'Twitter',
    date: '2026-09-16',
    topic: 'AI',
    subtopic: 'Tools',
    format: 'List',
    title: 'Best AI Development Tools in 2026',
    summary: 'Curated list of essential AI development tools',
    targetAudience: 'Developers',
    views: 6200,
    likes: 289,
    comments: 45,
    shares: 78,
    saves: 145,
    engagementRate: 9.0,
    outcome: 'medium'
  },
  {
    postId: 'post_036',
    platform: 'LinkedIn',
    date: '2026-09-17',
    topic: 'Python',
    subtopic: 'Automation',
    format: 'Tutorial',
    title: 'Automate Excel Reports with Python',
    summary: 'Generate professional Excel reports programmatically',
    targetAudience: 'Developers',
    views: 9800,
    likes: 534,
    comments: 87,
    shares: 145,
    saves: 278,
    engagementRate: 10.7,
    outcome: 'high'
  },
  {
    postId: 'post_037',
    platform: 'LinkedIn',
    date: '2026-09-18',
    topic: 'DevOps',
    subtopic: 'Terraform',
    format: 'Tutorial',
    title: 'Infrastructure as Code with Terraform Basics',
    summary: 'Getting started with Terraform for infrastructure management',
    targetAudience: 'Developers',
    views: 5800,
    likes: 256,
    comments: 42,
    shares: 68,
    saves: 123,
    engagementRate: 8.4,
    outcome: 'medium'
  },
  {
    postId: 'post_038',
    platform: 'Twitter',
    date: '2026-09-19',
    topic: 'Cybersecurity',
    subtopic: 'Awareness',
    format: 'Thread',
    title: 'Common Security Mistakes Developers Make',
    summary: 'Overview of security anti-patterns',
    targetAudience: 'Developers',
    views: 4100,
    likes: 167,
    comments: 28,
    shares: 45,
    saves: 78,
    engagementRate: 7.8,
    outcome: 'medium'
  },
  {
    postId: 'post_039',
    platform: 'LinkedIn',
    date: '2026-09-20',
    topic: 'AI',
    subtopic: 'Practical Tutorial',
    format: 'Tutorial',
    title: 'Build a Code Review Bot with AI',
    summary: 'Automate code reviews using large language models',
    targetAudience: 'Developers',
    views: 11200,
    likes: 612,
    comments: 98,
    shares: 178,
    saves: 334,
    engagementRate: 10.9,
    outcome: 'high'
  },
  {
    postId: 'post_040',
    platform: 'Twitter',
    date: '2026-09-21',
    topic: 'Cloud',
    subtopic: 'Serverless',
    format: 'Thread',
    title: 'When NOT to Use Serverless',
    summary: 'Honest discussion about serverless limitations',
    targetAudience: 'Developers',
    views: 7800,
    likes: 389,
    comments: 67,
    shares: 112,
    saves: 189,
    engagementRate: 9.7,
    outcome: 'high'
  },
  {
    postId: 'post_041',
    platform: 'LinkedIn',
    date: '2026-09-22',
    topic: 'Python',
    subtopic: 'Web Development',
    format: 'Tutorial',
    title: 'FastAPI vs Flask: Complete Comparison',
    summary: 'Performance and feature comparison of Python web frameworks',
    targetAudience: 'Developers',
    views: 8100,
    likes: 423,
    comments: 76,
    shares: 123,
    saves: 223,
    engagementRate: 10.4,
    outcome: 'high'
  },
  {
    postId: 'post_042',
    platform: 'LinkedIn',
    date: '2026-09-23',
    topic: 'AI',
    subtopic: 'News',
    format: 'News',
    title: 'Major AI Breakthrough Announced',
    summary: 'Coverage of recent AI research announcement',
    targetAudience: 'General Tech',
    views: 3800,
    likes: 134,
    comments: 19,
    shares: 32,
    saves: 56,
    engagementRate: 6.3,
    outcome: 'medium'
  },
  {
    postId: 'post_043',
    platform: 'Twitter',
    date: '2026-09-24',
    topic: 'DevOps',
    subtopic: 'Git',
    format: 'Thread',
    title: 'Git Commands You Need to Know',
    summary: 'Essential Git commands with real-world examples',
    targetAudience: 'Students',
    views: 9400,
    likes: 567,
    comments: 89,
    shares: 167,
    saves: 298,
    engagementRate: 11.9,
    outcome: 'high'
  },
  {
    postId: 'post_044',
    platform: 'LinkedIn',
    date: '2026-09-25',
    topic: 'Cybersecurity',
    subtopic: 'Practical Demo',
    format: 'Tutorial',
    title: 'JWT Authentication: Implementation and Security',
    summary: 'Complete guide to implementing secure JWT authentication',
    targetAudience: 'Developers',
    views: 10600,
    likes: 589,
    comments: 92,
    shares: 167,
    saves: 289,
    engagementRate: 10.7,
    outcome: 'high'
  },
  {
    postId: 'post_045',
    platform: 'LinkedIn',
    date: '2026-09-26',
    topic: 'Cloud',
    subtopic: 'Database',
    format: 'Guide',
    title: 'Choosing the Right Database for Your Project',
    summary: 'Decision framework for database selection',
    targetAudience: 'Developers',
    views: 6900,
    likes: 312,
    comments: 54,
    shares: 89,
    saves: 156,
    engagementRate: 8.9,
    outcome: 'high'
  },
];

export const brandProfile = {
  name: 'TechNova',
  industry: 'Technology Education',
  focusAreas: ['AI', 'Python', 'Cybersecurity', 'Cloud Computing', 'DevOps'],
  targetAudience: 'Students, developers, and young professionals interested in technology',
  brandVoice: {
    tone: 'Practical, simple, and friendly',
    style: 'Technically accurate but accessible',
    characteristics: [
      'Avoids unnecessary jargon',
      'Focuses on practical applications',
      'Provides concrete examples',
      'Maintains a conversational yet professional tone',
      'Emphasizes hands-on learning'
    ]
  },
  contentGoals: [
    'Educate developers on emerging technologies',
    'Provide actionable tutorials and guides',
    'Build a community of learners',
    'Establish thought leadership in tech education'
  ]
};

export const initialAudiencePreferences = {
  preferredContentTypes: [
    'Step-by-step tutorials',
    'Practical code examples',
    'Real-world demonstrations',
    'Performance comparisons'
  ],
  lessEngagingContentTypes: [
    'Generic news summaries',
    'Abstract theory without examples',
    'Generic awareness posts',
    'Opinion pieces without practical value'
  ],
  topicPreferences: {
    high: ['AI practical tutorials', 'Python automation', 'Practical cybersecurity demos'],
    medium: ['Cloud architecture', 'DevOps tools', 'Technology news'],
    low: ['Generic awareness posts', 'Abstract discussions without examples']
  }
};
